"""
Day 14 — runs all 10 of Section 23's failure scenarios and writes the
real result to `results/day14_failure_scenarios.json` (S7: generated by
running real code, never hand-typed).

Run: python -m autopilot_shadow.failure_scenarios.build_failure_report
"""

from __future__ import annotations

import json
from pathlib import Path

from .scenarios import run_all

RESULTS_DIR = Path(__file__).resolve().parents[3] / "results"


def build() -> dict:
    results = run_all()
    n_passed = sum(1 for r in results if r.passed)
    report = {
        "n_cases": len(results),
        "n_passed": n_passed,
        "all_passed": n_passed == len(results),
        "cases": [r.as_dict() for r in results],
    }
    RESULTS_DIR.mkdir(exist_ok=True)
    (RESULTS_DIR / "day14_failure_scenarios.json").write_text(json.dumps(report, indent=2, default=str))
    return report


if __name__ == "__main__":
    report = build()
    print(f"FAILURE SCENARIOS: {report['n_passed']} / {report['n_cases']} fail safely\n")
    for case in report["cases"]:
        mark = "PASS" if case["passed"] else "FAIL"
        print(f"  [{mark}] {case['case_id']}: {case['name']}")
